// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "GoToAngle.h"
GoToAngle::GoToAngle(float ang) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::trunnion);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	angle = ang;
}
// Called just before this Command runs the first time
void GoToAngle::Initialize() {
	
}
// Called repeatedly when this Command is scheduled to run
void GoToAngle::Execute() {
	if(abs(angle - Robot::trunnion->GetAngle()) > 5) {
		if(Robot::trunnion->GetAngle() > angle) {
			Robot::trunnion->ChangeAngle(Trunnion::DOWN);
		}
		else {
			Robot::trunnion->ChangeAngle(Trunnion::UP);
		}
	}
}
// Make this return true when this Command no longer needs to run execute()
bool GoToAngle::IsFinished() {
	if(abs(angle - Robot::trunnion->GetAngle()) > 5) {
		return false;
	}
	else {
		return true;
	}
}
// Called once after isFinished returns true
void GoToAngle::End() {
	Robot::trunnion->Stop();
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void GoToAngle::Interrupted() {
}
