// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "ClawLED.h"
#include "../Robotmap.h"
#include "../Commands/ClawLEDLightUp.h"
ClawLED::ClawLED() : Subsystem("ClawLED") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	lEDControl = RobotMap::clawLEDLEDControl;
	lEDPhotoEye = RobotMap::clawLEDLEDPhotoEye;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void ClawLED::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new ClawLEDLightUp());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
bool ClawLED::IsBallIn() {
	return lEDPhotoEye->Get();
}
void ClawLED::SetLEDStatus(bool on) {
	if(on == true) {
		lEDControl->Set(Relay::kForward);
	} else {
		lEDControl->Set(Relay::kReverse);
	}
}
