// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef TRUNNION_H
#define TRUNNION_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class Trunnion: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	static const double MAX;
	static const double MIN;
public:
	enum AngleDirection { UP, DOWN, STOP };
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* armMotor;
	AnalogChannel* armAngle;
	Solenoid* brake;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Trunnion();
	void InitDefaultCommand();
	void ChangeAngle(AngleDirection angleDirection);
	void Lock(bool lock);
	float GetAngle();
	void Stop();
};
#endif
